user_valid:
   max_length_name: 50
   max_length_email: 255
   min_length_password: 6
gravatar: 80
remember_me: 1
gravatar_for_user: 50
pagination:
   number_user_per_page: 10
piture_size: 5
validates_micropost_content: 140
micropost_gravatar: 50
user_info_gravatar: 50
image_height: 400 
image_width: 400
